Oracle pool
eclipse-vertx/vertx-sql-client pull request #1128
Opened 2022-02-01 14:46 UTC by tsegismont

Fixes #1127

2022-02-01 14:50 UTC, tsegismont commented
@Sanne would you mind having a look at this PR? In particular, could you confirm that nothing else is needed beyond the content of the last commit in order to comply with the JDBC API requirements regarding connection pooling?

2022-02-01 15:34 UTC, Sanne commented on vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleConnection.java
> +    if (handler != null) {
so what happens when the handler is null? My guess is a connection is eventually opened, and it's leaked?

In that case, wouldn't it be better for this code to throw an exception before attempting to connect?

2022-02-01 16:23 UTC, tsegismont commented
>Before I do, could you clarify why you mention JDBC API ? Why does it matter in this context?

The Reactive Oracle Client is different than the other Vert.x SQL clients because it is built atop the Oracle JDBC driver.
And, since JDBC 4.3, connections pools shall invoke `beginRequest`/`endRequest` (see https://dba.stackexchange.com/a/208215 and https://groups.google.com/g/r2dbc/c/zZ09hFMR9N8/m/aTKoFU8pBwAJ)

2022-02-02 10:56 UTC, vietj commented
I would like the before/after oracle specific connection event to be moved from the `Connection` interface to a subclass of `SqlConnectionPool` for oracle that would handle this with a hook so all happens in a single place and does not affect other implementation that do not need this.

2022-02-02 10:57 UTC, vietj requested changes
I would like the before/after oracle specific connection event to be moved from the `Connection` interface to a subclass of `SqlConnectionPool` for oracle that would handle this with a hook so all happens in a single place and does not affect other implementation that do not need this.

2022-02-09 07:55 UTC, vietj commented
ping @tsegismont

2022-02-09 15:20 UTC, tsegismont commented
@vietj please take a look at the last commit.

It adds a flag to the connection object indicating whether pool hooks should be used.
In order to avoid too much complexity, the flag is only used in the fast track where the potential performance penalty can be important.

2022-02-10 09:11 UTC, vietj commented
after reconsidering, I think it is more clean to add 2 functions (`Function<Connection, Future<Void>`) for the lifecycle in the SqlConnectionPool class for this matter instead of adding this to the `Connection` interface

2022-02-11 17:10 UTC, tsegismont commented
@vietj PTAL

2022-02-14 09:08 UTC, merged

2022-02-14 23:07 UTC, Sanne commented
awesome :100: