Clear MySQL prepared statements cache on connection reset
eclipse-vertx/vertx-sql-client pull request #1428
Opened 2024-03-12 16:41 UTC by tsegismont

See #1424

Otherwise, the client emits an error such as:

```
io.vertx.mysqlclient.MySQLException: {errorMessage=Unknown prepared statement handler (1) given to mysql_stmt_precheck, errorCode=1243, sqlState=HY000}
```

2024-03-12 16:41 UTC, tsegismont commented
@vietj I'll backport this to `4.x` after the PR is merged

2024-03-13 08:41 UTC, vietj commented on vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/cache/LruCache.java
>  public class LruCache<K, V> extends LinkedHashMap<K, V> {
missing tests in `LruCacheTest`

2024-03-13 08:42 UTC, vietj requested changes
Good job, missing tests in LruCacheTest

2024-03-13 10:58 UTC, tsegismont commented on vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/cache/LruCache.java
>  public class LruCache<K, V> extends LinkedHashMap<K, V> {
Done

2024-03-13 14:57 UTC, tsegismont commented
Done

2024-03-13 15:16 UTC, vietj approved these changes

2024-03-13 15:43 UTC, merged