Add json element accessor for row
eclipse-vertx/vertx-sql-client pull request #816
Opened 2020-11-29 01:21 UTC by BillyYccc

fixes #815

2020-11-30 14:02 UTC, vietj commented
I'm wondering if we should not just call this `getJson` instead ?

currently JsonArray and JsonObject do have a `getValue` method.

what's your opinion @pmlopes ?

2020-11-30 14:15 UTC, vietj commented
I've done a quick research and we use the term _json_ most of the time when we need this meaning:

- WebClient `HttpRequest#sendJson(Object, ...)`
- Schema: `Object getJson()`
- Schema Router: `addJson(String, Object)`
- Buffer : `toJson()`
- JsonPointer : `Object queryJson()`
- data object `toJson()`
- `RoutingContext#json(Object)`

so we should use `getJson`

2020-11-30 14:17 UTC, vietj commented on vertx-sql-client/src/main/java/io/vertx/sqlclient/Row.java
> +   *   <li>Null</li>
`Null` is not a type, instead it should be `might be {@code null} or one of the following types:`

2020-11-30 14:18 UTC, vietj requested changes
A couple of concerns to address

2020-11-30 14:20 UTC, vietj commented
and of course I know it's not a change you did and it was already in the API. So it's a fix before 4.0.0 is released.

2020-11-30 14:22 UTC, vietj commented
Actually now I remember why I named this "getJsonElement", the main reason is that the `getJsonArray` is conflicting with the actual `getJsonArray` naming....

2020-11-30 14:23 UTC, vietj commented
so we need to settle on a decision to keep `element` or use `value` I think

2020-11-30 14:52 UTC, vietj commented
one possibility is to rename array (which are rarely used in practice) to `getArrayOfXXX` which would give us : `getArrayOfJson` / `getArrayOfJsonArray`

2020-11-30 15:12 UTC, BillyYccc commented
I think `getArrayOfXXX` seems inconsistent which is not in the same pattern with the `getIntegerArray`, `getStringArray`...
I'm inclined to use the `getJsonElement` compared with `getJsonValue`.

2020-11-30 15:35 UTC, BillyYccc commented
We could also override the `toString` method for the `JSON_NULL` object which will return "null" string.

2020-11-30 19:57 UTC, vietj commented
@BillyYccc I updated master and 3.9 and renamed to `getArrayOf` so now you can rename to `getJson(K)` and `getArrayOfJson(K)`

2020-12-01 08:32 UTC, vietj commented
@BillyYccc can you rebase and rename to `getJson` and `getArrayOfJson` ?

2020-12-01 15:39 UTC, vietj commented on vertx-sql-client/src/main/java/io/vertx/sqlclient/Row.java
> +    return getArrayOfJson(pos);
should be `getArrayOfJsons`

2020-12-01 16:41 UTC, vietj approved these changes

2020-12-01 16:42 UTC, vietj commented
thanks @BillyYccc this PR raised a very relevant couple of issues to fix before 4.0.0 or live with it

2020-12-02 01:05 UTC, merged